### ISSUE TITLE
Html-encoded quotation marks

### ISSUE THREAD

**Issue by davimack** [purtuga/generator-sharepoint-spa#5]
Peppered throughout are html-encoded quotation marks, rather than just quotes.  Please follow your own deployment instructions & have a look at the output.  For example, in my generated require.config.json file I end up with the following: `&#34;SPWidgets&#34;: &#34;vendor/SPWidgets/src&#34;`

Obviously, this needs changed to `"SPWidgets":  "vendor/SPWidgets/src"`

**Comment by purtuga** [comment]
hi @davimack  - thanks for reporting this. 
I will take a look at it soon.

**Comment by purtuga** [comment]
Looks like I [fixed](https://github.com/purtuga/generator-sharepoint-spa/commit/fca1dc01811783c666a34beb14c5bc613c68999a#diff-69f863e820208b96ac29dd7c87eafd12R8) this a while back, but never pushed a new release to NPM. 

To get around the issue temporarily, you can install directly from github using:

```bash
npm i -D purtuga/generator-sharepoint-spa
```
then just run the generator as usual. 

I will publish a new version to NPM soon.

**Comment by davimack** [comment]
Awesome!  Thank you!

**Comment by purtuga** [comment]
v0.1.2 has been published to npm with needed fixes. 
Thanks for reporting this.
